### ISSUE TITLE
[HELP] Question: are the integrase (IntI) always on the opposite strand of gene cassettes?

### ISSUE THREAD

**Issue by jiarong** [gem-pasteur/Integron_Finder#101]
Hi, I noticed a few cases in IF2 (v2.0.2) results that have IntI and gene cassettes on  the same strand.  All examples I seen in literature has integrase on the opposite strand of gene cassettes. Should these cases with IntI and gene cassettes on the same strand be kept as true integron? Thanks!

**Comment by jeanrjc** [comment]
Hello,

Inverted integron-integrases have already been described before IntegronFinder came out (https://www.sciencedirect.com/science/article/abs/pii/S0966842X07001023). In the original paper for IF, we describe that we found some of them across the integrase tree : 

> a group of integrons displaying an integron-integrase in the same orientation as the attC
sites (inverted integron-integrase group) was previously described as a monophyletic group (7), but in our analysis it was clearly paraphyletic (Supplementary Figure S2, column F). Notably, in addition to the previously identified inverted
integron-integrase group of certain Treponema spp., a class 1 integron present in the genome of Acinetobacter baumannii 1656-2 had an inverted integron-integrase.

They are true integron in the sense that they have an integrases and attC sites. They might or might not be as effective as other integrons, or maybe they don't even recombine at all, I'm not sure if they were experimentally tested. Anyway, you can still filter them out easily if you don't want to include them in your analysis.

**Comment by jiarong** [comment]
Thanks for quick reply!

**Comment by jiarong** [comment]
Hi, I have follow up Q:
I am seeing cases that intI and gene cassettes on the opposite strand but facing inwards:
--intI--> ... <--attC--
The typical examples in literatures are facing outwards:
<--intI-- ... --attC-->

Any suggestions on the cases facing inwards?
