### ISSUE TITLE
[BUG] IF crashes with --gbk option in a specific caase

### ISSUE THREAD

**Issue by eloilit** [gem-pasteur/Integron_Finder#104]
**Describe the bug**
When using the --gbk option, IF crashes if a feature (e.g. cassette, attC site) spans over both borders of a replicon.

**To Reproduce**
With the attached files
1. integron_finder --local-max --mute --outdir ./IFResults --gembase --gembase-path ./Gembase --gbk ./Gembase/Replicons/KLPN001.0321.00476.P003.fst
2. See error

**Expected behavior**

Finish without error and produce output files

**Screenshots**

![image](https://user-images.githubusercontent.com/34735700/197213083-a132cb77-0983-4c5a-b8fd-c4776ce0ca33.png)

**Please complete the following information):**

***OS:*** 

 - [ ] Linux
 - [ ] Windows
 - [X] Mac

***Integron_Finder Version:***

integron_finder version 2.0.2
Using:
 - Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ]
 - numpy 1.19.4
 - pandas 1.1.5
 - matplolib 3.3.3
 - biopython 1.78

 - Prodigal V2.6.3: February, 2016
 - INFERNAL 1.1.4 (Dec 2020)
 - HMMER 3.3.2 (Nov 2020); http://hmmer.org/

**Additional context**
Not a big issue, as it works properly if we remove the --gbk option

**Comment by eloilit** [comment]
[Gembase.zip](https://github.com/gem-pasteur/Integron_Finder/files/9839640/Gembase.zip)

**Comment by jeanrjc** [comment]
> a feature (e.g. cassette, attC site) spans over both borders of a replicon

You mean, that the feature exists in the circular replicon and is cut in 2 in the linear sequence ?

**Comment by eloilit** [comment]
Yes ! Here's an extraction of the .integrons file in my specific case. You can see that the last protein detected begins at position 190392 and ends at position 299
![image](https://user-images.githubusercontent.com/34735700/197520740-61c740e6-a5a5-4e13-8a42-85bcf83d44a0.png)
