### ISSUE TITLE
[HELP] How can I get the sequence of whole integron?

### ISSUE THREAD

**Issue by Galib009** [gem-pasteur/Integron_Finder#105]
I want to get the full sequence of the integron including the gene cassette, is there any option or way to get the sequence from fasta/multi-fasta file? 

Many Thanks for this tool
- Kazi

**Comment by jeanrjc** [comment]
Hello,

With the option --gbk, you can extract the features of the integrons annotated, which you may convert with any gbk parser. 

Alternatively, if you're familiar with bash, you can do the following :

```bash
# get position for the integron integron_01 in replicon : myreplicon
positions=$(awk 'BEGIN{min=9999999; max=0}$1=="integron_01" && $2=="myreplicon"{if ($4<min) {min=$4}; if ($5>max) {max=$5}}END{print min".."max}' Results_Integron_Finder_myreplicon/*integrons)

# extract sequence with esl-sfetch (gets installed with hmmer, so you should have it)
# first create index for fasta file (need to be done once)
esl-sfetch --index myreplicon.fst
# extract sequence
esl-sfetch -c $positions myreplicon.fst myreplicon > integron_01_myreplicon.fst
```

**Comment by Galib009** [comment]
Hi Jean,
Thank you for your reply. However, I am facing this error after the last command "Didn't find sequence myreplicon in the index" -
![integron_finder_error](https://user-images.githubusercontent.com/57619312/198934203-bdcbce05-30c6-4a5f-add8-faf0980f27a8.png)

here, I have attached the screenshot of the myreplicon.integrons file - 

![screenshot_myreplicon_integrons](https://user-images.githubusercontent.com/57619312/198934677-b0b7fdf6-28f3-4554-8d27-7fa4293a63a7.png)

- Kazi

**Comment by jeanrjc** [comment]
use `$2=="contig_4"` in you case instead of `$2=="myreplicon"`

You can also do it by hand and do `esl-sfetch -c 1681061..1684879 myreplicon.fst contig_4 > integron_01_contig_4.fst`

if you do `echo $positions` it should return 1681061..1684879 (at least it's supposed to)
