### ISSUE TITLE
[BUG] underlay of /etc/localtime required more than 50 (87) bind mounts

### ISSUE THREAD

**Issue by yegonzalezflores** [gem-pasteur/Integron_Finder#107]
Good morning. Since Friday, I'm trying to run the Integron Finder tool from your Galaxy server, and I keep obtaining the same error (**underlay of /etc/localtime required more than 50 (87) bind mounts**). At first I thought it was something related to the data I was trying to analyse, but today I tried with data I had previously succesfully analysed using the Galaxy server Integron Finder and the same parameters and now I obtain the same error. Therefore, I suspect it could be an internal problem. Thank you very much in advance.

**Comment by bneron** [comment]
Integron_finder is executed inside an Apptainer container for the galaxy version.
The message is raised by the container and not Integron_Finder, it should be a simple warning and not an error.
I will check what's happen with the galaxy teams.

**Comment by bneron** [comment]
The Galaxy version has been fixed.
You can submit new jobs.

**Comment by yegonzalezflores** [comment]
Thank you very much. Now it works perfectly.
