### ISSUE TITLE
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'

### ISSUE THREAD

**Issue by EllBaum** [gem-pasteur/Integron_Finder#108]
Version of Integron_Finder:
2.0

OS
 Linux

Expected behavior
Output of the "integron_finder -h" command.

Actual behavior
Error message about the Bio.Seq lacking the IUPAC attribute.

Steps to reproduce behavior
$ integron_finder -h
Traceback (most recent call last):
  File env/bin/integron_finder", line 7, in <module>
    from integron_finder.scripts.finder import main
  File "env/lib/python3.10/site-packages/integron_finder/scripts/finder.py", line 51, in <module>
    from integron_finder import utils
  File "env/lib/python3.10/site-packages/integron_finder/utils.py", line 62, in <module>
    read_multi_prot_fasta = make_multi_fasta_reader(Seq.IUPAC.extended_protein)
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'

The package was installed via conda on an external server and the Biopython version is 1.78, as stated on the dependency list, and does not contain the module alphabet with the IUPAC attribute.

I would much appreciate your help resolving this issue.

Thank you,

Ella Baumer

**Comment by bneron** [comment]
try with IF version 2.0.2 which should fix this problem

**Comment by EllBaum** [comment]
Thank you!
