### ISSUE TITLE
How to classify Integrons？

### ISSUE THREAD

**Issue by xdli009** [gem-pasteur/Integron_Finder#116]
Hello,

I would like to know if this tool can classify integrons, for example, distinguishing which ones are class 1 integrons.

Thank you so much!

**Comment by jeanrjc** [comment]
Hello,

Using the option `--promoter-attI` will annotate known promoters and attI sites from integrons classe 1, 2, 3 (when known). Otherwise, IntegronFinder does not classify integrons other than complete/CALINs/In0.
