### ISSUE TITLE
error python-pandas-0.19

### ISSUE THREAD

**Issue by johrollin** [gem-pasteur/Integron_Finder#34]
Bonjour,

Nous avons installé IntegronFinder et nous avons eu un problème pour le faire fonctionner:

Commande utilisée: 

`integron_finder ACIAD.fasta
`
Message d'erreur:
```
integrons_describe.to_csv(os.path.join(out_dir_ok, outfile), sep="\t", index=0, fillna="NA")

TypeError: to_csv() got an unexpected keyword argument 'fillna'
```

Sur la documentation de python-pandas 0.18 et 0.19, nous n'avons pas trouvé l'argument "fillna" pour la fonction to_csv().
Pour y remédier nous avons modifié integronfinder.py de la manière suivante:

ligne 1746
`integrons_describe.to_csv(os.path.join(out_dir_ok, outfile), sep="\t", index=0, na_rep="NA")`

Après cette modification, tout semble fonctionner normalement.
Ce changement vous semble-t-il pertinent ?

Cordialement,
J.Rollin & P.Amours
LABGeM/Génoscope

**Comment by bneron** [comment]
quelle version d'integrons_finder avez vous utilisé?

car ce bug est déja corrigé sur master
https://github.com/gem-pasteur/Integron_Finder/blob/master/integron_finder#L1773

Bertrand Néron

**Comment by johrollin** [comment]
Nous avons la version 1.5.0
Nous allons update en version 1.5.1

merci pour la réponse rapide
