### ISSUE TITLE
help --gembase 

### ISSUE THREAD

**Issue by johrollin** [gem-pasteur/Integron_Finder#35]
Bonjour,

Nous souhaitons utiliser IntegronFinder en ayant nos propres annotations de gènes, par conséquent, sans utiliser Prodigal. Pour cela nous avons essayé --gembase, sans succès.
IntegronFinder ne semble pas pouvoir lire de multi-fasta, or, le gembase qui contiendrait les annotations protéiques devrait être multi-fasta. 

Est-ce bien l'utilisation prévue pour --gembase ?
Quel serait l'alternative pour pouvoir détecter les intégrons avec nos propres annotations/prédictions de protéines?

Cordialement,
J.Rollin & P.Amours.
LABGeM/Génoscope

**Comment by jeanrjc** [comment]
Bonjour,

Pour l'instant il n'y a pas d'option pratique pour utiliser vos annotations. L'option `--gembase` est essentiellement une option pour utilisation interne.  Cela dit, vous avez 2 options:

1. Créer vos fichiers de protéines en amont, et faire en sorte qu'ils soient au bon endroit pour satisfaire la condition [de présence du fichier au bon endroit](https://github.com/gem-pasteur/Integron_Finder/blob/master/integron_finder#L1047:L1049). La seule autre condition pour que ça marche est de respecter le format de description du header fasta fourni par prodigal pour que le parseur fonctionne, à savoir:

     ```
     > ID_PROTEIN # 556 # 771 # -1 # whatever
     MYPROTEINSEQ....
    ```

où 

- 556 = Start : nombre entier
- 771 = End : nombre entier
- -1 = complementary strand : {-1, 1}

Je pense que c'est le plus simple.

2. Vous pouvez essayer avec l'option `--gembase` mais il faut respecter un plus grand nombre de conditions que précédemment, notamment avoir une architecture de dossier spécifique et un header du fasta différent. 

Dites moi si l'option 1 ne marche pas, et on avisera ensuite.

Cordialement,
Jean Cury

**Comment by johrollin** [comment]
Merci pour la réponse rapide, nous allons essayer l'option 1, nous vous tenons au courant.

**Comment by johrollin** [comment]
Bonjour,
Nous avons testé l'option 1 qui semble fonctionner, nous arrivons à obtenir les prédictions d'intégrons avec nos annotations.
Nous allons, donc utiliser IntegronFinder via cette méthode pour le moment. 
Pensez vous qu'il soit possible d'implémenter à l'avenir une fonctionnalité qui permettrait de prendre le fichier de protéines en entrée du programme (et donc d'éviter à avoir à le placer dans les dossiers de résultats) ?

Merci pour votre aide

J.Rollin & P.Amours.
LABGeM/Génoscope

**Comment by cachapuz2001** [comment]
Nous y réfléchissons !
Cordialement,
Eduardo

**Comment by bneron** [comment]
fix this issue by providing two new options 
--prot-file path to the protein file in fasta format
--annot-parser path to a python script to parse the sequence ids 
see  https://integronfinder.readthedocs.io/en/latest/user_guide/tutorial.html#custom-protein-file
