### ISSUE TITLE
Find integrons in a multiple sequence fasta file

### ISSUE THREAD

**Issue by koopkaup** [gem-pasteur/Integron_Finder#36]
Hi
Could you add the option to find integrons in a fasta file with multiple sequences (assembled contigs)?

**Comment by jeanrjc** [comment]
Hi,

Thanks for your input. We're planning to add this feature. 

Meanwhile, you can split your multi-fasta and loop over each single fasta file to search for integrons.  

Best,
Jean

**Comment by jeanrjc** [comment]
Closing to remove duplicated issue. Issue #41 is the main issue now.
