### ISSUE TITLE
Parallelisation

### ISSUE THREAD

**Issue by asetGem** [gem-pasteur/Integron_Finder#44]
- [ ] Provided parallelisation:
    - Ask user for a maximum number of threads to use.
    - Spread those threads between hmmer/infernal run and number of replicons processed at the same time.

- [ ] Cluster parallelisation: add information in doc to run integron_finder on the cluster on a big dataset (split dataset and run job_array)

**Comment by bneron** [comment]
instead to parallelize with threads, create parallel_integron_finder which is a workflow using nextflow.
This allow to scale up easily for instance on cluster or use singularity images.
