### ISSUE TITLE
Add threshold of number of attC to keep a CALIN

### ISSUE THREAD

**Issue by asetGem** [gem-pasteur/Integron_Finder#45]
- [x] By default, keep only CALINs with at least 2 attC sites.

- [ ] Add option `--single-attc` to keep all CALINs even if only 1 attC
instead to add option `--single-attc` add more versatile option `--calin-threshold` to keep only calin with attC number greater than this value.

**Comment by bneron** [comment]
instead of --single-attc option add --attc-threshold which allow to specify any number of calin
