### ISSUE TITLE
stdout/stderr management

### ISSUE THREAD

**Issue by asetGem** [gem-pasteur/Integron_Finder#47]
- [x] silence prodigal stderr

- [x] Change stdout of integron_finder: at the end of the processing of a replicon, print a line with: `<range>/<#replicons> <replicon_ID> <#integrons> <#in0> <#CALIN>`

**Comment by bneron** [comment]
> Change stdout of integron_finder: at the end of the processing of a replicon, print a line with: <range>/<#replicons> <replicon_ID> <#integrons> <#in0> <#CALIN>

can you explicit what is <range> <#replicons> on so on.
if you can give an example of the desired output, it will be great

**Comment by jeanrjc** [comment]
Well, I don't remember or what @asetGem meant, but I guess it could be an incremental number in case of multifasta. Like how many replicons have been processed so far.

A desired output would look like:

```
#    replicon_id   N_integrons    N_In0    N_CALIN 
1    replicon_01                   1           0                 1
2    replicon_02                   2           1                 5
```

There should be an option to switch it off too, in case there are tons of sequences.

**Comment by bneron** [comment]
done in summary file
