### ISSUE TITLE
Prediction over sequence start with --linear

### ISSUE THREAD

**Issue by johrollin** [gem-pasteur/Integron_Finder#55]
Hello,

On few bacteria, integron_finder find an integron over the sequence start even if the "--linear" option is active.
```
FEATURES          Location/Qualifiers
    integron      join(1591485..1621862,1..7622)
                  /integron_id="integron_01"
                  /integron_type="complete"
```
If I understand the "--linear" option correctly this should not append, right ?

Here is the command line we used:

`integron_finder $fnafile --local_max --cpu 1 --linear`

Nothing very specific there, but we still use the "gembase workaround" (https://github.com/gem-pasteur/Integron_Finder/issues/35), I don't think it impact this issue.

If needed I can provide data for further test.

J.Rollin
LABGeM/Génoscope

**Comment by jeanrjc** [comment]
Hello, 

Indeed, it shouldn't happen. It might be already fixed in version 2.0. 
We'll let you know when it's fixed.

Best,
Jean

**Comment by duboism** [comment]
Hello,

Any news on this bug ?

**Comment by duboism** [comment]
Hello,

IIUC, the bug is solved in version 2, right ?

**Comment by bneron** [comment]
Yes, I will very soon (one or two days) release a new version.
