### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mdtorohernando** [gem-pasteur/Integron_Finder#62]
## Version of Integron_Finder:

integron_finder version 1.5.1
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]

 - open-source GPLv3,
 - Jean Cury, Betrand Néron, Eduardo Rocha,
 - citation:

 Identification and analysis of integrons and cassette arrays in bacterial genomes
 Jean Cury; Thomas Jove; Marie Touchon; Bertrand Neron; Eduardo PC Rocha
 Nucleic Acids Research 2016; doi: 10.1093/nar/gkw319
 

### OS

- [X] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

integron finder output from multifasta file (assembled contigs)

## Actual behavior

```
azken@azken-mdt2:/media/azken/RAID5/8_Contigs$ integron_finder chr_C6840.fa 
Traceback (most recent call last):
  File "/usr/local/bin/integron_finder", line 1608, in <module>
    alphabet=Seq.IUPAC.unambiguous_dna)
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/__init__.py", line 712, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle
```

## Steps to reproduce behavior

integron_finder multifasta.fa

**Comment by jeanrjc** [comment]
Hello, to use multi fasta files, you need to use IntegronFinder version 2. It is not released officially yet, but you can install it and use it. See Issue #57 for how to install the version 2.

**Comment by mdtorohernando** [comment]
Thank you very much for your quick response!
