### ISSUE TITLE
Trouble installing integron_finder using pip install

### ISSUE THREAD

**Issue by aaron-bio** [gem-pasteur/Integron_Finder#63]
Having some trouble installing integron_finder using pip. Also noticed that the version available on pip is 1.5.1 instead of 2.0.

## Version of Integron_Finder: 1.5.1

Write here the output of integron_finder --version.

### OS

- [ ] Linux
- [ ] Windows
- [X] Mac (Python 3.7)

## Actual behavior

Could not install integron_finder with pip install

## Steps to reproduce behavior

Tried installing integron_finder using pip command: pip install integron_finder

## Relevant logs and/or screenshots

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/zzqx0b4s18j2754q6c7yjs7h0000gw/T/pip-install-rl7de4dj/integron-finder/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/zzqx0b4s18j2754q6c7yjs7h0000gw/T/pip-install-rl7de4dj/integron-finder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/j6/zzqx0b4s18j2754q6c7yjs7h0000gw/T/pip-install-rl7de4dj/integron-finder/
    Complete output (1 lines):
    Sorry, Python 3 is not supported yet
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jeanrjc** [comment]
Hello, 
IntegronFinder version 2 is not released officially yet, but you can install it and use it. See Issue #57 for how to install the version 2.
You need python 2.7 for the version 1.5, I guess that's why it failed.
