### ISSUE TITLE
summary files should be created when no integron is found

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/Integron_Finder#66]
**observation**: the .summary file is not created when no integrons is found.
**consequences**: upon merging we only have replicons with integrons. We should have all replicons, even when there is no integron. When multifasta file, it should output every replicon, with 0,0,0 if no integron are found.
**impact**: minimal.

**Comment by bneron** [comment]
what do you expect in summary?
a normal summary looklike
```
ID_replicon     ID_integron     complete        In0     CALIN
SEQ1    integron_01     0       1       0
SEQ1    integron_02     0       0       1
SEQ2    integron_01     0       0       1
```
just the header?
```
ID_replicon     ID_integron     complete        In0     CALIN
```

**Comment by jeanrjc** [comment]
I expect (linked with issue #67): 
```
ID_replicon     complete        In0     CALIN
SEQ3    0    0    0
```

So upon merging with your normal summary would give:
```
ID_replicon     complete        In0     CALIN
SEQ1     0       1       0
SEQ1     0       0       1
SEQ2     0       0       1
SEQ3     0       0       0
```

Fixing issue #67 would give:
```
ID_replicon     complete        In0     CALIN
SEQ1     0       1       1
SEQ2     0       0       1
SEQ3     0       0       0
```
