### ISSUE TITLE
ID_integron should not be in .summary file 

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/Integron_Finder#67]
**observation**: a line in the .summary file contains "ID_replicon, ID_integron, Complete, In0, CALIN".
**consequences**: the value taken by complete, In0 and CALIN can only be 0,0,1/0,1,0/1,0,0, whereas one might expect for a given replicon the number of complete/In0/CALIN, not what each integron is.
**impact**: minimal.

**Comment by bneron** [comment]
fix by f6a1a16
