### ISSUE TITLE
problem with overlapping/near identical attC sites

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/Integron_Finder#69]
**observation**: we may find 2 attC that are detected with the beginning of the 2nd attC that starts before the first attC ends:

ID_integron|	ID_replicon	|element	|pos_beg|	pos_end	|strand	|evalue	|distance_2attC
-|	-	|-	|-|	-	|-	|-	|-
integron_01|	VIVU001.C.00013.C001	|attc_014	|169308**3**	|1693209	|-1.0	|0.099	|339
integron_01|	VIVU001.C.00013.C001	|attc_015	|169308**4**	|1693209	|-1.0	|0.017	|3310967

**Consequence**: 2nd attC is one too many. The distance reported is thus wrong.

**impact**: minimal

We should remove duplicate for on `pos_beg` or `pos_end` [here](https://github.com/gem-pasteur/Integron_Finder/blob/c27caf3bda72720be8f94d9aaa192e6c27736ffb/integron_finder/attc.py#L60), not just `pos_beg`.

**Comment by bneron** [comment]
can you provide data to integrate them in tests?

**Comment by jeanrjc** [comment]
Hi @bneron,
I think you have access to VIVU001.C.00013.C001, let me know if you can't reproduce the issue.

**Comment by bneron** [comment]
I haven't access to VIVU001.C.00013.C001

**Comment by bneron** [comment]
does the strand is important to determine duplicates?

**Comment by bneron** [comment]
if we remove attc sites which have pos_beg and pos_end close (less than 3 bases diff)
what should the behavior if we have 3 attc with the following pos_beg/pos_end

Accession_number | cm_attC | cm_debut | cm_fin | pos_beg | pos_end | sens | evalue
--------------------------|------------|-------------|----------|------------|------------|-------|----------
ACBA.007.P01_13 |  attc_4 |  1 | 47 | 5500 | 7000 | + | 1.100000e-07 
ACBA.007.P01_13 |  attc_4 |  1 | 47 | 5502 | 7002 | + | 1.100000e-04 
ACBA.007.P01_13 |  attc_4 |  1 | 47 | 5504 | 7004 | + | 1.100000e-03

* The second attc is at less than 3 bases than the first one and should be removed ?
* The third attc is at less than 3 bases than the second one but more than 3 bases than the first one so should we remove or keep it ?

**Comment by cachapuz2001** [comment]
> does the strand is important to determine duplicates?

I would say it is not. They are partly palindromic. I would suggest just check the overlap. 

> * The second attc is at less than 3 bases than the first one and should be removed ?
> * The third attc is at less than 3 bases than the second one but more than 3 bases than the first one so should we remove or keep it ?
My opinion: one should remove all that overlap more than 50% of the size. I.e. take the best one and remove those that overlap more than 50%
