### ISSUE TITLE
Integron classes 1,2,3

### ISSUE THREAD

**Issue by koopkaup** [gem-pasteur/Integron_Finder#75]
Does Integron finder have Int1, Int2 and Int3 profiles in the model files and if they are found in the metagenome then results will show each class separately?

**Comment by jeanrjc** [comment]
Hello, 
no, there is a single intI profile covering all intI. However, class 1, 2, 3 attI are annotated as such when found, as well as class 1 and 3 Pc. 

Alternatively, if you have specific profiles or sequences for specific classes, you could annotate all intI found by IF with these specific profiles.

Best
