### ISSUE TITLE
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'

### ISSUE THREAD

**Issue by bfrancescol** [gem-pasteur/Integron_Finder#78]
## Version of Integron_Finder:

1.5.1

### OS

- [ ] Linux
- [ ] Windows
- [X ] Mac

## Expected behavior

Output of the "integron_finder -h" command.

## Actual behavior

Error message about the Bio.Seq lacking the IUPAC attribute.

## Steps to reproduce behavior

[bfroliveira@bioinfomicro ~]$ integron_finder -h
Traceback (most recent call last):
  File "/home/bfroliveira/miniconda3/bin/integron_finder", line 7, in <module>
    from integron_finder.scripts.finder import main
  File "/home/bfroliveira/miniconda3/lib/python3.7/site-packages/integron_finder/scripts/finder.py", line 51, in <module>
    from integron_finder import utils
  File "/home/bfroliveira/miniconda3/lib/python3.7/site-packages/integron_finder/utils.py", line 62, in <module>
    read_multi_prot_fasta = make_multi_fasta_reader(Seq.IUPAC.extended_protein)
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'

I have installed using conda (I am the user of an external server) and the Biopython is updated (despite I don't know if this includes the IUPAC attribute in Bio.Seq module).

Thank you very much if you could help me with this issue.

Kind regards,
Bruno Francesco.

**Comment by tigerxu** [comment]
Hi, 

I have the same issue. Any suggestion to solve it.

Many thanks
Zhuofei

**Comment by jeanrjc** [comment]
Hello,

We are in the process of finishing the release of version IFv2.

In the meantime, to use it, one can use a conda virtual environment, to have a clean installation of IntegronFinder v2:

```bash
conda create --name IFv2 python=3.6 # faut pas prendre une version trop avancée de python non plus ^^
conda config --add channels bioconda # if it's not already the case
conda activate IFv2    
conda install integron_finder # install integron_finder
conda install biopython==1.72 # downgrade biopython and pandas waiting for upcoming fixes
conda install pandas=0.25.3
integron_finder ...
conda deactivate
<do something else with other version of python packages>
<come back later and anywhere>
conda activate IFv2
integron_finder ....
```

Within the environment, `integron_finder -V` should give you ` integron_finder version 2.0rc6`

Thanks for reporting

**Comment by tigerxu** [comment]
Great! I have installed IFv2 using conda. Thank you very much!

**Comment by bneron** [comment]
fixed with last version of integron_finder on Master
