### ISSUE TITLE
program not work for Staphylococcus aureus

### ISSUE THREAD

**Issue by WMBio** [gem-pasteur/Integron_Finder#83]
integron_finder version 2-2021-04-21
- [ ] Linux

Integron_finder were used for over 900 complete assembled Staphylococcus aureus genomes from NCBI，the program running ok, but None Integron found.  While some other species look like ok. Is this normal, or there is a bug? Thanks!

**Comment by jeanrjc** [comment]
Hello, 

If you did not encounter any error it's likely that your dataset does not contain any integron.  

Besides, it is known that Firmicutes do not contain integron (or on an exceptional basis), see Cury et al. 2016, Fig 5, where no integrons were found in >500 Firmicutes genomes (including some S. aureus).
