### ISSUE TITLE
Fatal error: Exit code 127 ()

### ISSUE THREAD

**Issue by IustinBilavschi** [gem-pasteur/Integron_Finder#86]
### OS

- [ ] Linux
- [x] Windows
- [ ] Mac

## Expected behavior

I am using IntegronFinder via GalaxyPasteur website portal in Google Chrome. Until today, it worked perfectly. I uploaded some bacterial complete genomes and it showed wich contained integrons until today.

## Actual behavior

Today, when i uploaded some Aeromonas caviae genomes, i execute the program, and it shows this: 
"Fatal error: Exit code 127 ()
error: Integron_Finder requires module(s) < hmmer/3.2.1 infernal/1.1.3 prodigal/2.6.3 > to be loaded first

Loading Integron_Finder/1.5.1
  ERROR: Module evaluation aborted
error: Integron_Finder requires module(s) < hmmer/3"

## Steps to reproduce behavior

- I upload the genomes
- I execute the program
- The error appears.

**Comment by jeanrjc** [comment]
@IustinBilavschi The galaxy server has been fixed !
