### ISSUE TITLE
[BUG] IntegronFinder fails when there is a "space" in the path

### ISSUE THREAD

**Issue by eloilit** [gem-pasteur/Integron_Finder#99]
**Describe the bug**
On a Mac, IntegronFinder bugs when there is a "space" character in the path to the genome file

**To Reproduce**
1. Create a path with a space included (e.g. /user/Genus species/genome.fasta
2. integron_finder --local-max genome.fasta

**Expected behavior**

Normal run

**Please complete the following information):**

***OS:*** 

 - [ ] Linux
 - [ ] Windows
 - [X] Mac

***Integron_Finder Version:***

  copy/paste here the output of integron_finder --version

integron_finder version 2.0.2
Using:
 - Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ]
 - numpy 1.19.4
 - pandas 1.1.5
 - matplolib 3.3.3
 - biopython 1.78

 - Prodigal V2.6.3: February, 2016
 - INFERNAL 1.1.4 (Dec 2020)
 - HMMER 3.3.2 (Nov 2020); http://hmmer.org/

**Additional context**
It's not truly important, but could be the source of a problem with people having few experience with bioinformatics

**Comment by bneron** [comment]
fixed with commit 5ae0c90
